#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color    "#2E3440"
bspc config focused_border_color    "#E5E9F0"
bspc config focus_follows_pointer   true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a Thunderbird desktop='5'

# Polybar goes here, and it should reload when bspwm is reloaded
~/.config/polybar/launch.sh &

# Remove the "X" cursor default on bspwm
xsetroot -cursor_name left_ptr &
